'use strict';

// Safe tuning knobs for Builder behavior and visuals.
module.exports = Object.freeze({
  DEBUG_SAY: false,
  DEBUG_DRAW: true,
  HOME_RICH_ENERGY: 5000,
  HOME_LOW_ENERGY: 1000,
  PICKUP_MIN: 50,
  SRC_CONTAINER_MIN: 100,

  HANDOFF_ENABLED: true,
  HANDOFF_REQUEST_TTL: 25,
  HANDOFF_ASSIGN_TTL: 40,
  HANDOFF_WAIT_TTL: 10,
  HANDOFF_MIN_RECEIVER_FREE: 25,
  HANDOFF_DEBUG_SAY: false,

  BUILDER_HANDOFF_WAIT_UNASSIGNED_TICKS: 5,
  BUILDER_HANDOFF_WAIT_IF_NEAR_TARGET_RANGE: 3,

  EMERGENCY_SELF_HARVEST_ENABLED: true,
  SELF_HARVEST_ONLY_WITHOUT_STORAGE: true,
  SELF_HARVEST_AFTER_HANDOFF_WAIT: true,
  SELF_HARVEST_MIN_SOURCE_ENERGY: 100,
  SELF_HARVEST_DELIVER_AT_ENERGY: 50,

  BUILDER_STATES: Object.freeze({
    HARVEST: 'HARVEST',
    TRAVEL: 'TRAVEL',
    BUILD: 'BUILD',
    IDLE: 'IDLE'
  }),

  DRAW: Object.freeze({
    TRAVEL: "#8ab6ff",
    SOURCE: "#ffd16e",
    DROP_COLOR: "#ffe66e",
    GRAVE_COLOR: "#ffb0e0",
    FILL_COLOR: "#6effa1",
    IDLE_COLOR: "#bfbfbf",
    BUILD_COLOR: "#2ad1c9",
    SINK_COLOR: "#6ee7ff",
    WIDTH: 0.12,
    OPACITY: 0.45,
    FONT: 0.6
  })
});
