'use strict';

module.exports = [
  [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
  [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE],
  [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE],
  [CARRY,CARRY,MOVE]
];
