'use strict';

module.exports = {
  BACKUP_HARVEST_ENABLED: true,
  BACKUP_HARVEST_ONLY_WITHOUT_STORAGE: true,
  BACKUP_HARVEST_ONLY_WHEN_CRITICAL_FILL_EXISTS: true,
  BACKUP_HARVEST_MIN_SOURCE_ENERGY: 100,
  BACKUP_HARVEST_ASSIGN_TTL: 15,
  BACKUP_HARVEST_DELIVER_AT_ENERGY: 50,
  QUEEN_BOOTSTRAP_QUOTA_WITHOUT_STORAGE: 2,
  QUEEN_NORMAL_QUOTA: 1
};
