'use strict';

var Handoff = require('role.EnergyHandoff');

module.exports = Object.freeze({
  DEBUG_SAY: false,
  DEBUG_DRAW: false,
  PATH_REUSE: 25,
  MIN_HAUL_REQUEST_ENERGY: 300,
  URGENT_HAUL_REQUEST_ENERGY: 1600,
  REQUEST_STALE_TICKS: 50,
  RESERVATION_TTL: 25,
  MAX_TRUCKERS_PER_HOME: 3,
  LOCAL_TRUCKER_BASE_QUOTA: 2,
  LOCAL_CONTAINER_PICKUP_AT: 1000,
  LOCAL_CONTAINER_URGENT_AT: 1600,
  LOCAL_CONTAINER_CRITICAL_AT: 1900,
  MAX_TOTAL_TRUCKERS_PER_HOME: 6,
  MAX_TRUCKERS_PER_REMOTE: 2,
  TOWER_REFILL_AT_OR_BELOW: 0.70,
  HANDOFF_ENABLED: true,
  HANDOFF_MIN_TRUCKER_ENERGY: 25,
  HANDOFF_MIN_RECEIVER_FREE: 25,
  HANDOFF_MAX_RANGE: 30,
  HANDOFF_MAX_FAILS: 3,
  HANDOFF_ASSIGN_TTL: Handoff.HANDOFF.HANDOFF_ASSIGN_TTL,
  HANDOFF_WAIT_TTL: Handoff.HANDOFF.HANDOFF_WAIT_TTL,
  DELIVERY_STORAGE_FIRST: true,
  IDLE_RANGE: 3
});
