'use strict';

module.exports = Object.freeze({
  DEBUG_SAY: false,
  DEBUG_DRAW: false,
  PATH_REUSE: 25,
  MIN_HAUL_REQUEST_ENERGY: 300,
  URGENT_HAUL_REQUEST_ENERGY: 1600,
  REQUEST_STALE_TICKS: 50,
  RESERVATION_TTL: 25,
  MAX_TRUCKERS_PER_HOME: 3,
  MAX_TRUCKERS_PER_REMOTE: 2,
  TOWER_REFILL_AT_OR_BELOW: 0.70,
  DELIVERY_STORAGE_FIRST: true,
  IDLE_RANGE: 3
});
