'use strict';

// Safe tuning knobs for Upgrader behavior and role-specific debug visuals.
module.exports = Object.freeze({
  DEBUG_SAY: false,
  DEBUG_DRAW: true,
  SIGN_TEXT: "BeeNice Please.",
  PATH_REUSE: 40,
  SKIP_RCL8_IF_SAFE: false,
  RCL8_SAFE_TTL: 0,
  UPGRADE_BUDGET_ENABLED: true,
  UPGRADE_MIN_CREEPS: 1,
  UPGRADE_STORAGE_EXTRA_UPGRADERS_AT: 50000,
  UPGRADE_STORAGE_MAX_UPGRADERS_AT: 150000,
  UPGRADE_SPAWN_DEBUG: false,
  UPGRADE_RCL2_TARGET_WORK: 2,
  UPGRADE_RCL3_TARGET_WORK: 3,
  UPGRADE_RCL4_TARGET_WORK: 4,
  UPGRADE_RCL5_TARGET_WORK: 4,
  UPGRADE_RCL4_SURPLUS_TARGET_WORK: 6,
  UPGRADE_RCL5_SURPLUS_TARGET_WORK: 7,
  UPGRADE_SURPLUS_WORK_BONUS: 2,
  UPGRADE_CONSTRUCTION_EMERGENCY_SITE_COUNT: 10,
  UPGRADE_EMERGENCY_MAX_CREEPS: 1,
  UPGRADE_DOWNGRADE_DANGER_TICKS: 4000,
  UPGRADE_DOWNGRADE_WARNING_TICKS: 8000,
  UPGRADE_DOWGRADE_DANGER_TICKS: 4000,
  UPGRADE_DOWGRADE_WARNING_TICKS: 8000,
  UPGRADE_MAX_CREEPS_RCL2: 2,
  UPGRADE_MAX_CREEPS_RCL3: 3,
  UPGRADE_MAX_CREEPS_RCL4: 4,
  UPGRADE_MAX_CREEPS_DEFAULT: 4,

  HANDOFF_ENABLED: true,
  HANDOFF_REQUEST_TTL: 25,
  HANDOFF_ASSIGN_TTL: 40,
  HANDOFF_WAIT_TTL: 10,
  HANDOFF_MIN_RECEIVER_FREE: 25,
  HANDOFF_DEBUG_SAY: false,

  DRAW: Object.freeze({
    DROP: "#ffe66e",
    CTRL: "#8ab6ff",
    LINK: "#6ec1ff",
    STORE: "#6effa1",
    CONT: "#6effa1",
    IDLE: "#bfbfbf",
    WIDTH: 0.12,
    OPACITY: 0.45,
    FONT: 0.6
  })
});
