'use strict';
// owns: builder site bucket classification + scoring/select-best logic.
// does not own: room snapshot generation.
// called by: BeeSelectors facade, builder role code.
var BUILDER_SITE_BUCKETS={spawn:1,extension:1,tower:1,container:2,storage:2,terminal:2,link:2,road:3};
var BUILDER_BUCKET_BASE_SCORE={1:300,2:190,3:60};
function classifyBuilderSiteBucket(site){if(!site)return 3;return BUILDER_SITE_BUCKETS[site.structureType]||2;}
function findBuilderExtensionAnchor(room){if(!room)return null;var sp=room.find(FIND_MY_SPAWNS);if(sp&&sp.length)return sp[0];if(room.storage)return room.storage;if(room.terminal)return room.terminal;return null;}
function scoreConstructionSiteForBuilder(creep, site, opts){if(!creep||!site||!site.pos)return null;var o=opts||{};var bucket=classifyBuilderSiteBucket(site);var score=BUILDER_BUCKET_BASE_SCORE[bucket]||BUILDER_BUCKET_BASE_SCORE[2];var rd=Game.map.getRoomLinearDistance(creep.pos.roomName,site.pos.roomName,true);if(rd===0)score+=20;score-=rd*25;var range=(site.pos.roomName===creep.pos.roomName)?creep.pos.getRangeTo(site.pos):50;score-=Math.min(25,range*0.5);if(site.structureType===STRUCTURE_CONTAINER&&site.pos.findInRange(FIND_SOURCES,1).length>0){score+=130;bucket=1;}if(site.structureType===STRUCTURE_EXTENSION){var roomObj=site.room||Game.rooms[site.pos.roomName];var anchor=findBuilderExtensionAnchor(roomObj);if(anchor&&site.pos.inRangeTo(anchor.pos,6))score+=120;else{var sp=roomObj?roomObj.find(FIND_MY_SPAWNS):[];if(sp&&sp.length&&site.pos.inRangeTo(sp[0].pos,6))score+=120;}}if(site.progressTotal>0){score+=Math.floor((site.progress/site.progressTotal)*20);}if(o.stickyId&&site.id===o.stickyId)score+=(o.stickyBonus!=null)?o.stickyBonus:0;return{score:score,bucket:bucket,roomDistance:rd,range:range};}
function selectBestConstructionSiteForBuilder(creep, opts){if(!creep)return null;var best=null;for(var id in Game.constructionSites){if(!Object.prototype.hasOwnProperty.call(Game.constructionSites,id))continue;var site=Game.constructionSites[id];if(!site||!site.my)continue;var s=scoreConstructionSiteForBuilder(creep,site,opts);if(!s)continue;if(!best||s.score>best.score)best={site:site,score:s.score,bucket:s.bucket,roomDistance:s.roomDistance,range:s.range};}return best;}
module.exports={classifyBuilderSiteBucket:classifyBuilderSiteBucket,scoreConstructionSiteForBuilder:scoreConstructionSiteForBuilder,selectBestConstructionSiteForBuilder:selectBestConstructionSiteForBuilder};
